version: '2'
services:
  consul:
    image: consul
    ports:
    - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0

  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
    - STORAGE_TYPE=mysql
    - MYSQL_HOST=mysql
    ports:
    - 9411:9411
    depends_on:
    - storage

  zipkin-ui:
    image: openzipkin/zipkin-ui
    container_name: zipkin-ui
    environment:
    - ZIPKIN_BASE_URL=http://zipkin:9411
    ports:
    - 80:80
    depends_on:
    - zipkin



#  confluent/kafka

#  cachethq/docker
#  https://docs.cachethq.io/docs/get-started-with-docker