spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    consul:
      host: cbt-consul.apps.stg.azr-use2-pcf.cloud.bns
      port: 8080
      scheme: http

management:
  endpoints:
    web:
      exposure:
        include: "*"